### ISSUE TITLE
Able to change the level reported?

### ISSUE THREAD

**Issue by tonglil** [heroku/rollrus#2]
Is there a way to override the Levels() to make it report Warn or other levels?

https://github.com/heroku/rollrus/blob/master/rollrus.go#L77

**Comment by apg** [comment]
Not at the moment. If you're interested in opening a PR, I think it'd be
pretty simple to do the following:

1. Modify the Hook struct to have a []log.Level field
2. Move the []log.Level from Levels() into a var: defaultLevels
3. In Levels(), return defaultLevels if the levels field has len == 0,
otherwise the struct's levels.

And, of course a test should be added for it as well.

If you can't do it, I'll take a stab at it at some point in the future,
when my schedule permits.

**Comment by tonglil** [comment]
Thanks, I'll give it a try.

**Comment by apg** [comment]
Hi @tonglil, upon further inspection, it looks like that won't work exactly as presented. You'll need to create another SetupLogging function which allows you to pass in the levels.

**Comment by apg** [comment]
@tonglil can you try out the above branch and see if it solves your problem? I went ahead and fixed since I was looking at the code.

Thanks!

**Comment by tonglil** [comment]
Sorry about unable to trying it in time, but I just used it and it works great!

Thanks.

**Comment by apg** [comment]
No worries Tony! Glad it works for you!
